---
label: Produkt
hide_body: true
is_partial: false
fields:
- type: file
  name: productimage
  label: Produktbild
- type: textarea
  name: producttext
  label: Produkttext
  config:
    required: true
    wysiwyg: true
    schema:
      format: markdown
- type: text
  name: productlink
  label: Produktlink
- type: text
  name: produktlinktext
  label: Produktlink Text
pages:
- _products/test1.md
- _products/test2.md
- _products/test3.md
