---
label: Produktliste
hide_body: false
fields:
- type: list
  name: produktliste
  label: Produktliste
  config:
    min: '1'
    use_select: true
    source:
      type: pages
      section: produkte
  default: []
- type: color
  config:
    color_format: Hex
  default: "#6C7278"
