---
label: Produktliste
hide_body: true
is_partial: false
fields:
- type: list
  name: produktliste
  label: Produktliste
  config:
    min: '1'
    use_select: true
    source:
      type: pages
      section: banners-f16eb7c4-3f0d-473d-8273-9adf0e1c0676
pages:
- _products/test.md
