---
label: Produktliste
hide_body: true
fields:
- type: list
  name: produktliste
  label: Produktliste
  config:
    min: '1'
    use_select: true
    source:
      type: pages
      section: produkte
