---
label: Produkt
hide_body: true
fields:
- type: file
  name: productimage
  label: Produktbild
  default: "/uploads/2019/03/16/Black_Coffee_oBG.png"
- type: textarea
  name: producttext
  label: Produkttext
  config:
    required: true
    wysiwyg: true
    schema:
      format: markdown
  default: "**DER BEKANNTE**\n\nUnser Black Coffee überzeugt durch seine solide Basis.
    \  \nKlassisch Schwarz ohne Zusatz von Zucker oder Zusatzstoffe.   \nDer Cold
    Brew durchsticht mit seiner natürlich süßen Aromenvielfalt."
- type: text
  name: productlink
  label: Produktlink
- type: text
  name: produktlinktext
  label: Produktlink Text
- type: color
  config:
    color_format: Hex
  label: Produktfarbe
  name: productcolor
pages:
- _products/test3.md
- _products/test2.md
- _products/test1.md
