---
label: Produkt
hide_body: false
fields:
- type: file
  name: productimage
  label: Produktbild
  default: "/uploads/2019/03/16/Black_Coffee_oBG.png"
- type: textarea
  name: producttext
  label: Produkttext
  config:
    required: true
    wysiwyg: true
    schema:
      format: markdown
  default: "**DER BEKANNTE**\n\nUnser Black Coffee überzeugt durch seine solide Basis.
    \  \nKlassisch Schwarz ohne Zusatz von Zucker oder Zusatzstoffe.   \nDer Cold
    Brew durchsticht mit seiner natürlich süßen Aromenvielfalt."
- type: text
  name: produktlinktext
  label: Produktlink Text
- type: color
  config:
    color_format: Hex
  label: Produktfarbe
  name: productcolor
- type: color
  config:
    color_format: Hex
  label: Schriftfarbe
  name: fontColor
- type: text
  label: Name
  name: name
- type: text
  name: label
  label: Label
- type: text
  name: claim
  label: Claim
- type: text
  name: text
  label: Text
- type: text
  name: sweetLevel
  label: Süße
- type: text
  name: strongLevel
  label: Stärke
- type: file
  name: productimage1
  label: Produktbild 1
  default: "/uploads/2019/03/16/Black_Coffee_oBG.png"
- type: file
  name: productimage2
  label: Produktbild 2
  default: "/uploads/2019/03/16/Black_Coffee_oBG.png"
- type: file
  name: productimage3
  label: Produktbild 3
  default: "/uploads/2019/03/16/Black_Coffee_oBG.png"
- type: file
  name: consum1
  label: Konsumgelegenheit 1
  default: "/uploads/2019/03/16/Black_Coffee_oBG.png"
- type: file
  name: consum2
  label: Konsumgelegenheit 2
  default: "/uploads/2019/03/16/Black_Coffee_oBG.png"
- type: file
  name: consum3
  label: Konsumgelegenheit 3
  default: "/uploads/2019/03/16/Black_Coffee_oBG.png"
- type: select
  name: type
  config:
    source:
      type: simple
    options:
    - Coffee
    - Tea
  label: Typ
pages:
- _products/cold-brew-black.md
- _products/cold-brew-black-1.md
- _products/LatteMacchiato.md
- _products/BlackCoffee.md
